#!/bin/bash
# pipeline.sh

set -e

echo "Running Build Stage..."
sleep 2
echo "Build Successful ✅"

echo "Running Tests..."
sleep 2
echo "All Tests Passed ✅"

echo "Deploying Application..."
sleep 2
echo "Application Deployed Successfully 🚀"
